### ISSUE TITLE
Issues with pypy

### ISSUE THREAD

**Issue by bannsec** [zardus/mulpyplexer#10]
When installing angr-dev w/ pypy I get the following error from mulpyplexer

```
Installing wheels/keystone_engine-0.9.1.post3-py2.py3-none-linux_x86_64.whl
Processing ./wheels/keystone_engine-0.9.1.post3-py2.py3-none-linux_x86_64.whl
Installing collected packages: keystone-engine
Successfully installed keystone-engine-0.9.1.post3
[+] Install list:  mulpyplexer monkeyhex archinfo pyvex cle claripy ailment angr angr-management angrop pysoot angr-targets archr
[+] Installing mulpyplexer.
[-] pip-installing: -e mulpyplexer.
Looking in links: /home/angr/angr-dev/wheels
Obtaining file:///home/angr/angr-dev/mulpyplexer
Installing collected packages: mulpyplexer
  Running setup.py develop for mulpyplexer
    ERROR: Command errored out with exit status 1:
     command: /home/angr/.virtualenvs/angr-pypy/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/angr/angr-dev/mulpyplexer/setup.py'"'"'; __file__='"'"'/home/angr/angr-dev/mulpyplexer/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /home/angr/angr-dev/mulpyplexer/
    Complete output (30 lines):
    running develop
    /home/angr/.virtualenvs/angr-pypy/site-packages/setuptools/dist.py:476: UserWarning: Normalizing '0.09' to '0.9'
      normalized_version,
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/angr/angr-dev/mulpyplexer/setup.py", line 55, in <module>
        py_modules=['mulpyplexer']
      File "/home/angr/angr-dev/pypy/pypy3.7-v7.3.5-linux64/lib-python/3/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/angr/angr-dev/pypy/pypy3.7-v7.3.5-linux64/lib-python/3/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/home/angr/angr-dev/pypy/pypy3.7-v7.3.5-linux64/lib-python/3/distutils/dist.py", line 984, in run_command
        cmd_obj.ensure_finalized()
      File "/home/angr/angr-dev/pypy/pypy3.7-v7.3.5-linux64/lib-python/3/distutils/cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "/home/angr/.virtualenvs/angr-pypy/site-packages/setuptools/command/develop.py", line 56, in finalize_options
        easy_install.finalize_options(self)
      File "/home/angr/.virtualenvs/angr-pypy/site-packages/setuptools/command/easy_install.py", line 312, in finalize_options
        'install_lib', ('install_dir', 'install_dir')
      File "/home/angr/angr-dev/pypy/pypy3.7-v7.3.5-linux64/lib-python/3/distutils/cmd.py", line 287, in set_undefined_options
        src_cmd_obj.ensure_finalized()
      File "/home/angr/angr-dev/pypy/pypy3.7-v7.3.5-linux64/lib-python/3/distutils/cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "/home/angr/.virtualenvs/angr-pypy/site-packages/setuptools/command/install_lib.py", line 17, in finalize_options
        self.set_undefined_options('install',('install_layout','install_layout'))
      File "/home/angr/angr-dev/pypy/pypy3.7-v7.3.5-linux64/lib-python/3/distutils/cmd.py", line 290, in set_undefined_options
        setattr(self, dst_option, getattr(src_cmd_obj, src_option))
      File "/home/angr/angr-dev/pypy/pypy3.7-v7.3.5-linux64/lib-python/3/distutils/cmd.py", line 103, in __getattr__
        raise AttributeError(attr)
    AttributeError: install_layout
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/angr/.virtualenvs/angr-pypy/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/angr/angr-dev/mulpyplexer/setup.py'"'"'; __file__='"'"'/home/angr/angr-dev/mulpyplexer/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
[!!] pip failure (-e mulpyplexer). Check /tmp/setup-149 for details, or read it here:
```

**Comment by zardus** [comment]
I can recreate this with a fresh pypy venv, but upgrading setuptools (`pip install -U setuptools`) makes it work fine. Have you tried that?
